import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./components/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex min-h-screen bg-gray-100`}>
        <div>
        <Sidebar/>
        </div>
        
        {/* Main Content Area */}
        <div className="flex-1 p-14 overflow-y-auto lg:ml-[27%] xl:ml-[384px]">
          {children}
        </div>
      </body>
    </html>
  );
}
